### ISSUE TITLE
tool should not panic when no CLGs found

### ISSUE THREAD

**Issue by xh3b4sd** [xh3b4sd/clggen#7]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3190]

goroutine 1 [running]:
panic(0x19b700, 0xc420012140)
	/Users/xh3b4sd/.gvm/gos/go1.7.2/src/runtime/panic.go:500 +0x1a1
main.loadTemplates.func1(0x7fff5fbff5fb, 0xb, 0x0, 0x0, 0x29b5e0, 0xc420016900, 0xc420051b01, 0xc420012a00)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/common.go:19 +0x40
path/filepath.Walk(0x7fff5fbff5fb, 0xb, 0xc420012a00, 0x0, 0xc4200168d0)
	/Users/xh3b4sd/.gvm/gos/go1.7.2/src/path/filepath/path.go:396 +0x8b
main.loadTemplates(0x7fff5fbff5fb, 0xb, 0x0, 0x0, 0xc420051b58)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/common.go:34 +0xb2
main.(*clggen).ExecGenerateCmd(0xc4200142d0, 0xc42008e6c0, 0xc420010640, 0x0, 0x2)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/generate.go:38 +0x44
main.(*clggen).ExecGenerateCmd-fm(0xc42008e6c0, 0xc420010640, 0x0, 0x2)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/generate.go:22 +0x52
github.com/spf13/cobra.(*Command).execute(0xc42008e6c0, 0xc420010440, 0x2, 0x2, 0xc42008e6c0, 0xc420010440)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008e480, 0xc420051e08, 0xc42008e900, 0xc4200129a0)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc42008e480, 0xc420051e00, 0x1)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/spf13/cobra/command.go:681 +0x2b
main.(*clggen).Boot(0xc4200142d0)
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/main.go:82 +0xce
main.main()
	/Users/xh3b4sd/projects/private/anna/.workspace/src/github.com/xh3b4sd/clggen/main.go:105 +0x13a
service/clg/clg.go:7: running "clggen": exit status 2
make: *** [gogenerate] Error 1
```

**Comment by xh3b4sd** [comment]
Fixed.
